tunnel: bfb13583-f2b7-4419-80d6-9fa06fab7cda # Replace with your actual Tunnel UUID
credentials-file: /root/.cloudflared/bfb13583-f2b7-4419-80d6-9fa06fab7cda.json  # Ensure the correct path

ingress:
  - hostname: aaditya78.live
    service: http://localhost:5000  # Your Node.js server
  - service: http_status:404  # Default fallback
